development:
  adapter: postgresql
  host: localhost
  database: iom_development
  username: 
  password: 

test:
  adapter: postgresql
  host: localhost
  database: iom_test
  username: 
  password: 

staging:
  adapter: postgresql
  template: template_postgis
  encoding: unicode
  database: iom_production
  username: postgres
  password:

smbtc:
  adapter: postgresql
  template: template_postgis
  encoding: unicode
  database: iom_production
  username: postgres
  password:

production:
  adapter: postgresql
  template: template_postgis
  encoding: unicode
  host: localhost
  database: iom_production
  username: postgres
  password:
